export enum Role {
  INDIVIDUAL_USER = 'INDIVIDUAL_USER',
  COMPANY_ADMIN = 'COMPANY_ADMIN',
  COMPANY_ADMIN_EVIDENCE_CHECKER = 'COMPANY_ADMIN_EVIDENCE_CHECKER',
  EVIDENCE_CHECKER = 'EVIDENCE_CHECKER',
  APPLICANT = 'APPLICANT',
  COUNTER_SIGNATORY = 'COUNTER_SIGNATORY',
  SYSTEM_ADMIN = 'SYSTEM_ADMIN',
  REPRESENTATIVE = 'REPRESENTATIVE'
}
